name: SonarCloud analysis

on:
  pull_request:
    branches:
      - 'dev'
      - 'qa'
      - 'main'
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: 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  # Needed to get PR information
          SONAR_TOKEN: aefeaa120d80c1e292c598723ea9b6655a18d4d2   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
     